### ISSUE TITLE
Expanded regional dex Pokemon don't show their dex # in the summary screen

### ISSUE THREAD

**Issue by ZnogyroP** [DizzyEggg/PokeExpansion#3]
even after expanding the REGIONAL (not national) pokedex, only the first 202 pokemon show their dex numbers in the status screen

http://i.imgur.com/fDkmsr0.png
http://i.imgur.com/HPwRzSU.png

example of what i mean

(for the record, here's a pokemon within the first 202-)

http://i.imgur.com/c60zLvt.png

**Comment by ghost** [comment]
Fixed!
